---
services:
  radarr-cf-search:
    image: ghcr.io/thehesster/radarr-cf-search:latest
    container_name: radarr-cf-search
    environment:
      - CRON_SCHEDULE="* * * * *"
      - TZ=America/Los_Angeles
    volumes:
      - /path/to/config:/config # place your .env file in here
      